### ISSUE TITLE
Rename main app script

### ISSUE THREAD

**Issue by bernardmo** [oHead/mpr#3]
test.sh is no valid name for script. I suggest something like 'delete.sh'

**Comment by 4ants** [comment]
That is just confusing.
delete-all.sh is much more intuitive.

**Comment by Vedost** [comment]
Maybe delete-old-or-unused.sh.
It removes old OR unused tags, that's description.

**Comment by borisbabic** [comment]
+1

I wouldn't use .sh because of the bashisms present. It is misleading.

**Comment by oHead** [comment]
oh God :(
