### ISSUE TITLE
Windows 10 problem

### ISSUE THREAD

**Issue by 4ants** [oHead/mpr#8]
I have tried to execute this on Windows 10, but it does not work.
Don't know if it is related to issue: https://github.com/oHead/mpr/issues/4

Also, when I try to execute README file from Powershell nothing happens.
Will try to change extension from md to exe and try again.
I'll let you know if it works.

**Comment by antensoft** [comment]
+1

**Comment by Vedost** [comment]
+1

**Comment by borisbabic** [comment]
-1000

**Comment by nsoftproject** [comment]
+2
